version: '3'

services:
  gitea-db:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: giteapassword
      MYSQL_USER: gitea
      MYSQL_PASSWORD: gitea
      MYSQL_DATABASE: gitea
    volumes:
      - ./gitea-db:/var/lib/mysql
    networks:
      - gitea

  gitea:
    image: gitea/gitea:latest
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=gitea-db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    volumes:
      - ./gitea:/data
    ports:
      - "3000:3000"  # Puerto de Gitea web
      - "222:22"     # Puerto para SSH en Gitea
    depends_on:
      - gitea-db
    networks:
      - gitea

networks:
  gitea:
